name: My first workflow 
on:
  workflow_dispatch: 
jobs:
   my-first-job:
       runs-on: ubuntu-latest
       steps:
          - run: echo "This is my first workflow"
   my-second-job:
       runs-on: ubuntu-latest
       steps:
          - run: |
                  sleep 20;
                  echo "This is my second workflow"

          
